#!/usr/bin/env bash
# -l for show listening sockets
# -p for shows the PID and name of the program to which each socket belongs

if [ "$#" -lt "1" ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$1"
fi
