#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

i=1
while (( i <= 100 ))
do
    fizz="$((i % 3 == 0))"
    buzz="$((i % 5 == 0))"
    if (( fizz && buzz ))
    then
        echo "FizzBuzz"
    elif (( fizz ))
    then
        echo "Fizz"
    elif (( buzz ))
    then
        echo "Buzz"
    else
        echo $i
    fi
    (( i++ ))
done
