#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

i=0
while (( i < 10 ))
do
    case $i in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
        *)
            echo "Best School"
            ;;
done
