#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

hour=0
while (( hour <= 12 ))
do
    echo "Hour: $hour"
    min=1
    while (( min <= 59 ))
    do
        echo $min
        (( min++ ))
    done
    (( hour++ ))
done
