#!/usr/bin/env bash
# networking
# -i for edit in place

cp /etc/hosts ~/hosts.temp
sed -i "s/127.0.0.1/127.0.0.2/" ~/hosts.temp
sed -i "$ a 8.8.8.8 facebook.com\n" ~/hosts.temp
cp -f ~/hosts.temp /etc/hosts
